language: python
python:
  - "pypy"
  - "pypy3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "3.9-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.9-dev"
    - python: "nightly"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt

before_script:
  - chmod +x mock_server.sh
  - mock_server.sh &
script:
  - python3 -m unittest tests/unittestsPynav2.py